/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-11-22 at 03:35:07 UTC 
 * Modify at your own risk.
 */

package com.appspot.frogjump_cloud.frogjump;

/**
 * Service definition for Frogjump (v1).
 *
 * <p>
 * Frogjump backend service API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FrogjumpRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Frogjump extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the frogjump library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://frogjump-cloud.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "frogjump/v1/group/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Frogjump(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Frogjump(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Group collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Frogjump frogjump = new Frogjump(...);}
   *   {@code Frogjump.Group.List request = frogjump.group().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Group group() {
    return new Group();
  }

  /**
   * The "group" collection of methods.
   */
  public class Group {

    /**
     * Create a request for the method "group.create".
     *
     * This request holds the parameters needed by the frogjump server.  After setting any optional
     * parameters, call the {@link Create#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesCreateGroupRequest}
     * @return the request
     */
    public Create create(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesCreateGroupRequest content) throws java.io.IOException {
      Create result = new Create(content);
      initialize(result);
      return result;
    }

    public class Create extends FrogjumpRequest<com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse> {

      private static final String REST_PATH = "create";

      /**
       * Create a request for the method "group.create".
       *
       * This request holds the parameters needed by the the frogjump server.  After setting any
       * optional parameters, call the {@link Create#execute()} method to invoke the remote operation.
       * <p> {@link
       * Create#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesCreateGroupRequest}
       * @since 1.13
       */
      protected Create(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesCreateGroupRequest content) {
        super(Frogjump.this, "POST", REST_PATH, content, com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse.class);
      }

      @Override
      public Create setAlt(java.lang.String alt) {
        return (Create) super.setAlt(alt);
      }

      @Override
      public Create setFields(java.lang.String fields) {
        return (Create) super.setFields(fields);
      }

      @Override
      public Create setKey(java.lang.String key) {
        return (Create) super.setKey(key);
      }

      @Override
      public Create setOauthToken(java.lang.String oauthToken) {
        return (Create) super.setOauthToken(oauthToken);
      }

      @Override
      public Create setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Create) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Create setQuotaUser(java.lang.String quotaUser) {
        return (Create) super.setQuotaUser(quotaUser);
      }

      @Override
      public Create setUserIp(java.lang.String userIp) {
        return (Create) super.setUserIp(userIp);
      }

      @Override
      public Create set(String parameterName, Object value) {
        return (Create) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "group.join".
     *
     * This request holds the parameters needed by the frogjump server.  After setting any optional
     * parameters, call the {@link Join#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesJoinGroupRequest}
     * @return the request
     */
    public Join join(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesJoinGroupRequest content) throws java.io.IOException {
      Join result = new Join(content);
      initialize(result);
      return result;
    }

    public class Join extends FrogjumpRequest<com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse> {

      private static final String REST_PATH = "join";

      /**
       * Create a request for the method "group.join".
       *
       * This request holds the parameters needed by the the frogjump server.  After setting any
       * optional parameters, call the {@link Join#execute()} method to invoke the remote operation. <p>
       * {@link Join#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesJoinGroupRequest}
       * @since 1.13
       */
      protected Join(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesJoinGroupRequest content) {
        super(Frogjump.this, "POST", REST_PATH, content, com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse.class);
      }

      @Override
      public Join setAlt(java.lang.String alt) {
        return (Join) super.setAlt(alt);
      }

      @Override
      public Join setFields(java.lang.String fields) {
        return (Join) super.setFields(fields);
      }

      @Override
      public Join setKey(java.lang.String key) {
        return (Join) super.setKey(key);
      }

      @Override
      public Join setOauthToken(java.lang.String oauthToken) {
        return (Join) super.setOauthToken(oauthToken);
      }

      @Override
      public Join setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Join) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Join setQuotaUser(java.lang.String quotaUser) {
        return (Join) super.setQuotaUser(quotaUser);
      }

      @Override
      public Join setUserIp(java.lang.String userIp) {
        return (Join) super.setUserIp(userIp);
      }

      @Override
      public Join set(String parameterName, Object value) {
        return (Join) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "group.part".
     *
     * This request holds the parameters needed by the frogjump server.  After setting any optional
     * parameters, call the {@link Part#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPartGroupRequest}
     * @return the request
     */
    public Part part(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPartGroupRequest content) throws java.io.IOException {
      Part result = new Part(content);
      initialize(result);
      return result;
    }

    public class Part extends FrogjumpRequest<com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse> {

      private static final String REST_PATH = "part";

      /**
       * Create a request for the method "group.part".
       *
       * This request holds the parameters needed by the the frogjump server.  After setting any
       * optional parameters, call the {@link Part#execute()} method to invoke the remote operation. <p>
       * {@link Part#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPartGroupRequest}
       * @since 1.13
       */
      protected Part(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPartGroupRequest content) {
        super(Frogjump.this, "POST", REST_PATH, content, com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse.class);
      }

      @Override
      public Part setAlt(java.lang.String alt) {
        return (Part) super.setAlt(alt);
      }

      @Override
      public Part setFields(java.lang.String fields) {
        return (Part) super.setFields(fields);
      }

      @Override
      public Part setKey(java.lang.String key) {
        return (Part) super.setKey(key);
      }

      @Override
      public Part setOauthToken(java.lang.String oauthToken) {
        return (Part) super.setOauthToken(oauthToken);
      }

      @Override
      public Part setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Part) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Part setQuotaUser(java.lang.String quotaUser) {
        return (Part) super.setQuotaUser(quotaUser);
      }

      @Override
      public Part setUserIp(java.lang.String userIp) {
        return (Part) super.setUserIp(userIp);
      }

      @Override
      public Part set(String parameterName, Object value) {
        return (Part) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "group.post".
     *
     * This request holds the parameters needed by the frogjump server.  After setting any optional
     * parameters, call the {@link Post#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPostMessageRequest}
     * @return the request
     */
    public Post post(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPostMessageRequest content) throws java.io.IOException {
      Post result = new Post(content);
      initialize(result);
      return result;
    }

    public class Post extends FrogjumpRequest<com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse> {

      private static final String REST_PATH = "post";

      /**
       * Create a request for the method "group.post".
       *
       * This request holds the parameters needed by the the frogjump server.  After setting any
       * optional parameters, call the {@link Post#execute()} method to invoke the remote operation. <p>
       * {@link Post#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPostMessageRequest}
       * @since 1.13
       */
      protected Post(com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesPostMessageRequest content) {
        super(Frogjump.this, "POST", REST_PATH, content, com.appspot.frogjump_cloud.frogjump.model.FrogjumpApiMessagesGroupResponse.class);
      }

      @Override
      public Post setAlt(java.lang.String alt) {
        return (Post) super.setAlt(alt);
      }

      @Override
      public Post setFields(java.lang.String fields) {
        return (Post) super.setFields(fields);
      }

      @Override
      public Post setKey(java.lang.String key) {
        return (Post) super.setKey(key);
      }

      @Override
      public Post setOauthToken(java.lang.String oauthToken) {
        return (Post) super.setOauthToken(oauthToken);
      }

      @Override
      public Post setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Post) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Post setQuotaUser(java.lang.String quotaUser) {
        return (Post) super.setQuotaUser(quotaUser);
      }

      @Override
      public Post setUserIp(java.lang.String userIp) {
        return (Post) super.setUserIp(userIp);
      }

      @Override
      public Post set(String parameterName, Object value) {
        return (Post) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Frogjump}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Frogjump}. */
    @Override
    public Frogjump build() {
      return new Frogjump(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FrogjumpRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFrogjumpRequestInitializer(
        FrogjumpRequestInitializer frogjumpRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(frogjumpRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
