/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-11-22 at 03:35:07 UTC 
 * Modify at your own risk.
 */

package com.appspot.frogjump_cloud.frogjump.model;

/**
 * Model definition for FrogjumpApiMessagesPostMessageRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frogjump. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrogjumpApiMessagesPostMessageRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("gcm_token")
  private java.lang.String gcmToken;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("group_key")
  private java.lang.String groupKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long latE6;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long lngE6;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGcmToken() {
    return gcmToken;
  }

  /**
   * @param gcmToken gcmToken or {@code null} for none
   */
  public FrogjumpApiMessagesPostMessageRequest setGcmToken(java.lang.String gcmToken) {
    this.gcmToken = gcmToken;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupKey() {
    return groupKey;
  }

  /**
   * @param groupKey groupKey or {@code null} for none
   */
  public FrogjumpApiMessagesPostMessageRequest setGroupKey(java.lang.String groupKey) {
    this.groupKey = groupKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLatE6() {
    return latE6;
  }

  /**
   * @param latE6 latE6 or {@code null} for none
   */
  public FrogjumpApiMessagesPostMessageRequest setLatE6(java.lang.Long latE6) {
    this.latE6 = latE6;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLngE6() {
    return lngE6;
  }

  /**
   * @param lngE6 lngE6 or {@code null} for none
   */
  public FrogjumpApiMessagesPostMessageRequest setLngE6(java.lang.Long lngE6) {
    this.lngE6 = lngE6;
    return this;
  }

  @Override
  public FrogjumpApiMessagesPostMessageRequest set(String fieldName, Object value) {
    return (FrogjumpApiMessagesPostMessageRequest) super.set(fieldName, value);
  }

  @Override
  public FrogjumpApiMessagesPostMessageRequest clone() {
    return (FrogjumpApiMessagesPostMessageRequest) super.clone();
  }

}
